{
	"id": "oval:org.debian:def:60311498478729511628249595893093009161",
	"class": "patch",
	"metadata": {
		"title": "DSA-2880-1 python2.7",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 7",
			"product": "python2.7"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2013-4238",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4238"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2014-1912",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1912"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "\nMultiple security issues were discovered in Python:",
			"dsa": "DSA-2880",
			"date": "2014-03-17"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:1440",
								"comment": "python2.7 DPKG is earlier than 2.7.3-6+deb7u2"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 7 is installed"
			}
		]
	}
}
