{
	"id": "oval:org.debian:def:189922371531140375180665964063482909733",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2016-9013 python-django",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 11",
			"product": "python-django"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2016-9013",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-9013"
			}
		],
		"description": "Django 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3 use a hardcoded password for a temporary database user created when running tests with an Oracle database, which makes it easier for remote attackers to obtain access to the database server by leveraging failure to manually specify a password in the database settings TEST dictionary.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:10201",
								"comment": "python-django DPKG is earlier than 1:1.10.3-1"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 11 is installed"
			}
		]
	}
}
