{
	"id": "oval:org.debian:def:87938671271852024332661615025490347552",
	"class": "patch",
	"metadata": {
		"title": "DSA-4630-1 python-pysaml2",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 9",
			"product": "python-pysaml2"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2020-5390",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-5390"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "no info",
			"dsa": "DSA-4630",
			"date": "2020-02-21"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:2801",
								"comment": "python-pysaml2 DPKG is earlier than 3.0.0-5+deb9u1"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 9 is installed"
			}
		]
	}
}
