{
	"id": "oval:org.debian:def:104059898466194811988156369300985082776",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2020-13596 python-django",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 10",
			"product": "python-django"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2020-13596",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13596"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "It was discovered that Django, a high-level Python web development framework, did not properly sanitize input. This would allow a remote attacker to perform SQL injection attacks, Cross-Site Scripting (XSS) attacks, or leak sensitive information.",
			"dsa": "DSA-4705"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:18559",
								"comment": "python-django DPKG is earlier than 1:1.11.29-1~deb10u1"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 10 is installed"
			}
		]
	}
}
