{
	"id": "oval:org.debian:def:141181533467154812900847819296960275815",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2019-5010 python3.7",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 10",
			"product": "python3.7"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2019-5010",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5010"
			}
		],
		"description": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:17503",
								"comment": "python3.7 DPKG is earlier than 3.7.2-2"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 10 is installed"
			}
		]
	}
}
